### PR TITLE
[ci] use ubuntu-20

### PR DESCRIPTION
**Pull request by v1v**
### What

Use ubuntu-20 CI workers

### Why

Fix the failing ASP.NET MSSql tests on Linux

### Test

See [test-on-linux-ubuntu-20](https://apm-ci.elastic.co/job/apm-agent-dotnet/job/apm-agent-dotnet-mbp/job/PR-1303/2/execution/node/270/log/) didn't get timeout.

image

compared with

Screenshot 2021-05-24 at 12 50 17

### Further details

There are some stacktraces regarding the IO

```
[xUnit.net 00:01:18.52]       System.IO.IOException : The configured user limit (128) on the number of inotify instances has been reached.
[xUnit.net 00:01:18.52]       Stack Trace:
[xUnit.net 00:01:18.52]            at System.IO.FileSystemWatcher.StartRaisingEvents()
[xUnit.net 00:01:18.52]            at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
[xUnit.net 00:01:18.53]            at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
[xUnit.net 00:01:18.53]            at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
[xUnit.net 00:01:18.53]            at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
[xUnit.net 00:01:18.53]            at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
[xUnit.net 00:01:18.53]            at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__0_0()
[xUnit.net 00:01:18.53]            at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
[xUnit.net 00:01:18.53]            at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
[xUnit.net 00:01:18.54]            at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
[xUnit.net 00:01:18.54]            at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
[xUnit.net 00:01:18.54]            at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
[xUnit.net 00:01:18.54]            at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
[xUnit.net 00:01:18.54]         /var/lib/jenkins/workspace/net_apm-agent-dotnet-mbp_PR-1303/apm-agent-dotnet/test/Elastic.Apm.AspNetCore.Tests/DistributedTracingAspNetCoreTests.cs(41,0): at Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests.InitializeAsync()
```

### CODE REVIEW

**Review by mdelapenya — APPROVED** [review]

**Comment by russcam** [comment]
Looks like the MsSQL tests are failing because a connection cannot be established

```
Microsoft.Data.SqlClient.SqlException : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
```

**Review by cachedout — APPROVED** [review]

**Comment by v1v** [comment]
> Looks like the MsSQL tests are failing because a connection cannot be established

That particular issue started in the build [516](https://apm-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/apm-agent-dotnet/pipelines/apm-agent-dotnet-mbp/branches/master/runs/516/nodes/98/steps/274/log/?start=0), and the issue was even worst since it didn't finish but failed with a timeout. The related commit when things started to fail with the `SqlException` is  https://github.com/elastic/apm-agent-dotnet/commit/c2b519aaa0fe5e5044b736cfec695342f124bf30


On the other hand, I created a branch [`feature/test-latest-known-build`](https://github.com/elastic/apm-agent-dotnet/tree/feature/test-latest-known-build) that I branched off from f4eea73c9b0152a7375c1f87e98726c7f2f6f05d and applied the changes of this particular PR (to use ubuntu-20) and the `SqlException` is not there, see [here](https://apm-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/apm-agent-dotnet/pipelines/apm-agent-dotnet-mbp/branches/feature%252Ftest-latest-known-build/runs/1/nodes/194/steps/232/log/?start=0)

Therefore I'm inclined to say the root issue seems related to the code in terms of the SqlException.

What do you think?

**Review by kuisathaverat — APPROVED** [review]

**Comment by kuisathaverat** [comment]
> > Looks like the MsSQL tests are failing because a connection cannot be established
> 
> That particular issue started in the build [516](https://apm-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/apm-agent-dotnet/pipelines/apm-agent-dotnet-mbp/branches/master/runs/516/nodes/98/steps/274/log/?start=0), and the issue was even worst since it didn't finish but failed with a timeout. The related commit when things started to fail with the `SqlException` is [c2b519a](https://github.com/elastic/apm-agent-dotnet/commit/c2b519aaa0fe5e5044b736cfec695342f124bf30)
> 
> On the other hand, I created a branch [`feature/test-latest-known-build`](https://github.com/elastic/apm-agent-dotnet/tree/feature/test-latest-known-build) that I branched off from [f4eea73](https://github.com/elastic/apm-agent-dotnet/commit/f4eea73c9b0152a7375c1f87e98726c7f2f6f05d) and applied the changes of this particular PR (to use ubuntu-20) and the `SqlException` is not there, see [here](https://apm-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/apm-agent-dotnet/pipelines/apm-agent-dotnet-mbp/branches/feature%252Ftest-latest-known-build/runs/1/nodes/194/steps/232/log/?start=0)
> 
> Therefore I'm inclined to say the root issue seems related to the code in terms of the SqlException.
> 
> What do you think?

I ave tested those test on the CI and archiving the logs of the containers, they are up and running but the docker container cannot connect correctly to hist siblings. The solution is to not use DinD to run the .NET SDK is terrible slow with the .NET SDK 5 (about 7 times slower) this PR change to use the native SDK https://github.com/elastic/apm-agent-dotnet/pull/1301

**Comment by kuisathaverat** [comment]
BTW the increase in the time build is due to the SanitizeFieldNamesTests

Screenshot 2021-05-26 at 10 14 11

**Comment by russcam** [comment]
> Fix the failing ASP.NET MSSql tests on Linux

Unfortunately, it doesn't look like this fixes the failing MSSql tests on Linux; they're still failing with

```
Test: SqlClientListenerTests.Elastic.Apm.SqlClient.Tests.SqlClientListenerTests.SqlClientDiagnosticListener_ShouldCaptureErrorFromSystemSqlClient – Elastic.Apm.SqlClient.Tests.SqlClientListenerTests

Error
Microsoft.Data.SqlClient.SqlException : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
Stacktrace
```

which sounds like the SQL server docker container is successfully started, but the library cannot connect to it.
In contrast, on my local Windows machine, these tests all run successfully against SQL Server linux docker instances

sql_tests

docker_running_mssql

> That particular issue started in the build [516](https://apm-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/apm-agent-dotnet/pipelines/apm-agent-dotnet-mbp/branches/master/runs/516/nodes/98/steps/274/log/?start=0), and the issue was even worst since it didn't finish but failed with a timeout. The related commit when things started to fail with the `SqlException` is [c2b519a](https://github.com/elastic/apm-agent-dotnet/commit/c2b519aaa0fe5e5044b736cfec695342f124bf30)

Are we sure that is the first instance? There doesn't look to be any change in https://github.com/elastic/apm-agent-dotnet/commit/c2b519aaa0fe5e5044b736cfec695342f124bf30 related to the SQL tests. Could it coincide with a change in the CI environment that might affect docker in docker tests (I think I recall a change to disable ipv6 mentioned)?

**Comment by v1v** [comment]
> Are we sure that is the first instance?

Yes, that's what I saw when I debugged the logs and the test results.

> Could it coincide with a change in the CI environment that might affect docker in docker tests (I think I recall a change to disable ipv6 mentioned)?

I'll ask infra if there is anything related to the networking, but on the other hand, since the builds in the branch https://github.com/elastic/apm-agent-dotnet/tree/feature/test-latest-known-build didn't fail with the current CI environment, it looks suspicious.

**Comment by v1v** [comment]
There are some failures with some undefined variable

```
14:28:40 2021-06-07 13:28:40 - INFO:     googlecompute: fatal: [default]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible_distribution_release' is undefined\n\nThe error appears to be in '/infra/ansible/roles/azure-cli/tasks/linux/debian.yml': line 7, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: add the azure-cli apt repository\n  ^ here\n"}

```


image

**Comment by cachedout** [comment]
> I'll ask infra if there is anything related to the networking

@v1v Did you hear back from infra on this? Since this is related to an issue that we have marked as high-priority, I want to see if we can move forward here if possible. Thanks!

**Comment by kuisathaverat** [comment]
MsSQL test were fixed on https://github.com/elastic/apm-agent-dotnet/pull/1301

**Comment by cachedout** [comment]
> MsSQL test were fixed on #1301

@v1v Perhaps tests will pass here after a rebase?

**Comment by v1v** [comment]
I've just kicked off a build that should merge with the master branch by default. I'll also rebase this PR

**Comment by russcam** [comment]
> MsSQL test were fixed on #1301

Not running tests in a docker container for the Linux tests fixes the SQL tests. It does introduce another problem in that we now skip tests that make assertions that can only be performed when run inside a docker container (https://github.com/elastic/apm-agent-dotnet/commit/ada7a0c2d7beeef9d0b83946af8347d52e254ae1), so we lose coverage on those parts of the codebase.

**Comment by v1v** [comment]
I'll close this PR since master branch is now stable after the changes that Ivan and Russ applied in some other PRs

**Pull request closed without merging**
