### PR TITLE
Serialize payload to stream

### PR DESCRIPTION
**Pull request by russcam**
This commit updates PayloadSenderV2 to serialize the payload to a stream, reducing string allocations.

The stream could be backed by byte buffers rented from an array pool in future.

Add Deserialize method to PayloadItemSerializer for use in tests.

### CODE REVIEW

**Comment by russcam** [comment]
Since APM server supports chunked transfer encoding, we could use something like [`ObjectContent<T>`](https://github.com/mono/aspnetwebstack/blob/6248bfd24c31356e75a31c1b1030d4d96f669a6a/src/System.Net.Http.Formatting/ObjectContent.cs) and serialize to the request stream directly in future.

**Comment by russcam** [comment]
jenkins run the tests please

**Review by gregkalapos — APPROVED** [review]
LGTM

**Comment by russcam** [comment]
> The build fails in CI, but it's very strange 🤔

It looks like CI is running the result of merging in master branch. I've merged in master and fixed this, so this should now be good to merge, CI checks pending.

**Comment by russcam** [comment]
failing tests are unrelated, merging this in.

**Pull request merged**
