### PR TITLE
Added namespace import directive

### PR DESCRIPTION
**Pull request by shalvah**
This will reduce confusion, especially for people like myself who aren't very familiar with .NET and extension methods and may not be using an intelligent-enough IDE).

### CODE REVIEW

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by shalvah** [comment]
Signed.

**Comment by gregkalapos** [comment]
> Signed.

Thanks @shalvah  - small problem: our CLA checker is still not happy. Did you use the same username and mail address I see [here](https://patch-diff.githubusercontent.com/raw/elastic/apm-agent-dotnet/pull/660.patch) in the PR? You should use the same, otherwise it won't work. Sorry about the trouble.

**Comment by shalvah** [comment]
I used my GitHub email?

**Comment by gregkalapos** [comment]
Seems working now, thanks!

**Pull request merged**
