### PR TITLE
feat: Update Testcontainers for .NET to version 3.0.0

### LINKED ISSUE #123: .NET Core Linux not logging Entity Framework Core transactions
I published my app using:

```dotnet publish -r linux-x64 -f netcoreapp2.2 --self-contained -c Release```

The app works, requests end up in APM server, but no entity framework transactions.
Running the app from Rider on Windows works just fine. Is this a known thing with self-contained releases?

### PR DESCRIPTION
**Pull request by HofmeisterAn**
## What does this PR do?

Hi 👋, the pull request updates Testcontainers for .NET to its latest version 3.0.0 and replaces the legacy extension method modules with independent modules. Testcontainers and its transitive dependency, Docker.DotNet, are now using a strong name. It is likely that StrongNamer is no longer necessary.

## Why is it important?

The latest version contains many improvements and moves towards a stable API. New modules, improvements, and fixes will use the new API. There will be no more changes (support) to the old (legacy) approach.

## Related issues

\-

### CODE REVIEW

**Comment by HofmeisterAn** [comment]
The `MySqlCommandTests` should now run successfully.

**Comment by Mpdreamz** [comment]
Thanks for the update (and PR) @HofmeisterAn :+1: 

/test

**Comment by HofmeisterAn** [comment]
It looks like the comment did not trigger the test properly.

**Review by Mpdreamz — APPROVED** [review]
LGTM :+1: Thanks for updating us to the latest greatest TestContainers! :cat:

**Pull request merged**
