### PR TITLE
Fix/assembly metadata culture

### PR DESCRIPTION
**Pull request by russcam**
This PR fixes an issue with retrieving the assembly metadata locale.

In https://github.com/elastic/apm-agent-dotnet/pull/1708, the check for a nul terminating UTF-16 string was fixed, however,
 the locale was not correctly passed across the FFI boundary. This addresses that.

### CODE REVIEW

**Review by gregkalapos — APPROVED** [review]
Thank you!

**Comment by gregkalapos** [comment]
The new test fails in CI:

```
    [2022-05-30T10:42:51.990098598+00:00] [DEBUG] ModuleLoadFinished: 139996618369880 FSharp.Core.resources app domain 94813863203936 clrhost
    [2022-05-30T10:42:51.990517464+00:00] [DEBUG] ModuleLoadFinished: stored metadata for 139996618369880 FSharp.Core.resources app domain 94813863203936 clrhost
    [2022-05-30T10:42:51.996008388+00:00] [TRACE] ModuleLoadFinished: tracking 19 module(s)
    thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: MissingNulError { inner: Some([64368, 37779, 22075]) }', src/elastic_apm_profiler/src/interfaces/imetadata_assembly_import.rs:337:22
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', src/elastic_apm_profiler/src/profiler/mod.rs:1111:43
    fatal runtime error: failed to initiate panic, error 5
```

So far I can't reproduce this locally, the test is green on my machine.

**Comment by gregkalapos** [comment]
I think the problem is that those strings are not null terminated on Linux - opened https://github.com/elastic/apm-agent-dotnet/pull/1721 to handle it.

**Comment by russcam** [comment]
The u16 values in the array look suspicious; I'll try a different approach to get this. As far as I know, the string is nul terminated across all platforms.

**Pull request merged**
