### PR TITLE
update change log for 1.2.0 released version

### PR DESCRIPTION
**Pull request by vhatsura**
Does it need to be merged to `master` and then to `1.x` or vice versa?

/cc @bmorelli25, @gregkalapos

### CODE REVIEW

**Comment by gregkalapos** [comment]
> Does it need to be merged to `master` and then to `1.x` or vice versa?
> 
> /cc @bmorelli25, @gregkalapos

Oh, nice thx! 

The order doesn't really matter - we reset `1.x` for each minor release to master. Could you just open a PR with the same commit targeting `1.x`?

**Comment by gregkalapos** [comment]
I can't retrigger this build.. I hit the button in jenkins and nothing happens. 

Plus, there was a docsbuild step here, which is gone (I don't see it in #642) - I wanted to see that being green before I merge. 

Does anyone know why there is not docs build step anymore?

**Comment by gregkalapos** [comment]
> Plus, there was a docsbuild step here, which is gone (I don't see it in #642) - I wanted to see that being green before I merge.

@v1v, do you know something about this? ⬆️ Since when is the doc build step gone? 🤔

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by bmorelli25** [comment]
That's weird that it didn't automatically run. I was able to trigger it manually with the command in my previous comment.

**Comment by v1v** [comment]
@gregkalapos , not sure what the builddocs means. AFAIS, there is a GitHub check in the commit status:

image

Is that what you meant?

**Comment by bmorelli25** [comment]
@v1v The check didn't run (and didn't show up there) until I explicitly told it to with the command above:

```
@elasticmachine, run elasticsearch-ci/docs
```

**Comment by gregkalapos** [comment]
Brandon was faster to respond - exactly what he says. 

https://github.com/elastic/apm-agent-dotnet/pull/642 does not have that step either. I looked at some other PRs, those seem to have it.

**Comment by v1v** [comment]
Got it! Off the top of my head, that particular GH check wasn't there for different reasons:
- GitHub Webhook might not be triggered, or something related to GitHub itself.
- The `elasticsearch-ci` instance was down or missed the webhook event.

If the second one, then the docs team might get some insights about what's going on, although I'd say it was a kind of temporary spike if it happens again then we might need to contact the operations team who manages the `elasticsearch-ci`.  Does it sound like a good plan?

**Comment by gregkalapos** [comment]
Sounds good - I opened a PR ~an hour ago and that PR also has the`/docs`  check, so yeah, it seems working now.

**Comment by bmorelli25** [comment]
Thanks for the explanation! I let the docs team know as well.

**Pull request merged**
