### PR TITLE
[docs] Add EOL table

### PR DESCRIPTION
**Pull request by bmorelli25**
## What does this pull request do?

This PR defines end of life and end of maintenance dates for the .NET Agent. EOL dates were determined by going through old releases, finding the GA release date of the major .NET Agent versions, and adding 18 months.

## Why is it important?

We love all our products, but sometimes we must say goodbye to a release so that we can continue moving forward on future development and innovation.

## What does EOL/Maintenance mean?

> When a version goes out of maintenance, it is no longer guaranteed to get bug fixes. Between the end of maintenance and EOL, bug fixes will be discretionary, e.g. critical security issues. Once it's EOL, it's no longer given any support attention; issues related to it will be closed with WONTFIX.

## Related issues

For elastic/apm#173.

## Screenshots

Screen Shot 2020-02-18 at 11 20 22 AM

### CODE REVIEW

**Comment by bmorelli25** [comment]
That's a good point. As I see it, these dates aren't set in stone. We can adjust as needed, and move EOL further out if there's no new major version when the date starts getting closer.

**Comment by gregkalapos** [comment]
> That's a good point. As I see it, these dates aren't set in stone. We can adjust as needed, and move EOL further out if there's no new major version when the date starts getting closer.

👍 sounds good to me. Thanks.

**Comment by bmorelli25** [comment]
@gregkalapos. I messed up on the initial PR. EOL should include minors as well. That makes the date timeline much more realistic:
[options="header"]
|====
|Agent version |EOL Date |Maintained until
|1.0.x |2021-01-31 |1.1
|1.1.x |2021-04-01 |1.2
|1.2.x |2021-05-22 |1.3
|1.3.x |2021-08-12 |1.4
|====

**Comment by Bamieh** [comment]
# [Codecov](https://codecov.io/gh/elastic/apm-agent-dotnet/pull/731?src=pr&el=h1) Report
> Merging [#731](https://codecov.io/gh/elastic/apm-agent-dotnet/pull/731?src=pr&el=desc) into [master](https://codecov.io/gh/elastic/apm-agent-dotnet/commit/460b0078f3d56f677d194c5cb650293dac7ba2db&el=desc) will **increase** coverage by `6.31%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/elastic/apm-agent-dotnet/pull/731?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #731      +/-   ##
==========================================
+ Coverage   73.40%   79.72%   +6.31%     
==========================================
  Files         113      102      -11     
  Lines        5088     4685     -403     
==========================================
  Hits         3735     3735              
+ Misses       1353      950     -403     
```


| [Impacted Files](https://codecov.io/gh/elastic/apm-agent-dotnet/pull/731?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [...gnosticListener/AspNetCoreDiagnosticsSubscriber.cs](https://codecov.io/gh/elastic/apm-agent-dotnet/pull/731/diff?src=pr&el=tree#diff-c3JjL0VsYXN0aWMuQXBtLkFzcE5ldENvcmUvRGlhZ25vc3RpY0xpc3RlbmVyL0FzcE5ldENvcmVEaWFnbm9zdGljc1N1YnNjcmliZXIuY3M=) | | |
| [...lastic.Apm.AspNetCore/Extensions/ListExtensions.cs](https://codecov.io/gh/elastic/apm-agent-dotnet/pull/731/diff?src=pr&el=tree#diff-c3JjL0VsYXN0aWMuQXBtLkFzcE5ldENvcmUvRXh0ZW5zaW9ucy9MaXN0RXh0ZW5zaW9ucy5jcw==) | | |
| [src/Elastic.Apm.AspNetCore/AspNetCoreLogger.cs](https://codecov.io/gh/elastic/apm-agent-dotnet/pull/731/diff?src=pr&el=tree#diff-c3JjL0VsYXN0aWMuQXBtLkFzcE5ldENvcmUvQXNwTmV0Q29yZUxvZ2dlci5jcw==) | | |
| [...stic.Apm.AspNetCore/Extensions/StringExtensions.cs](https://codecov.io/gh/elastic/apm-agent-dotnet/pull/731/diff?src=pr&el=tree#diff-c3JjL0VsYXN0aWMuQXBtLkFzcE5ldENvcmUvRXh0ZW5zaW9ucy9TdHJpbmdFeHRlbnNpb25zLmNz) | | |
| [...Apm.AspNetCore/Extensions/TransactionExtentions.cs](https://codecov.io/gh/elastic/apm-agent-dotnet/pull/731/diff?src=pr&el=tree#diff-c3JjL0VsYXN0aWMuQXBtLkFzcE5ldENvcmUvRXh0ZW5zaW9ucy9UcmFuc2FjdGlvbkV4dGVudGlvbnMuY3M=) | | |
| [...c/Elastic.Apm.NetCoreAll/ApmMiddlewareExtension.cs](https://codecov.io/gh/elastic/apm-agent-dotnet/pull/731/diff?src=pr&el=tree#diff-c3JjL0VsYXN0aWMuQXBtLk5ldENvcmVBbGwvQXBtTWlkZGxld2FyZUV4dGVuc2lvbi5jcw==) | | |
| [src/Elastic.Apm.AspNetCore/ApmMiddleware.cs](https://codecov.io/gh/elastic/apm-agent-dotnet/pull/731/diff?src=pr&el=tree#diff-c3JjL0VsYXN0aWMuQXBtLkFzcE5ldENvcmUvQXBtTWlkZGxld2FyZS5jcw==) | | |
| [...Apm.AspNetCore/Config/MicrosoftExtensionsConfig.cs](https://codecov.io/gh/elastic/apm-agent-dotnet/pull/731/diff?src=pr&el=tree#diff-c3JjL0VsYXN0aWMuQXBtLkFzcE5ldENvcmUvQ29uZmlnL01pY3Jvc29mdEV4dGVuc2lvbnNDb25maWcuY3M=) | | |
| [...tic.Apm.AspNetCore/Extensions/RequestExtentions.cs](https://codecov.io/gh/elastic/apm-agent-dotnet/pull/731/diff?src=pr&el=tree#diff-c3JjL0VsYXN0aWMuQXBtLkFzcE5ldENvcmUvRXh0ZW5zaW9ucy9SZXF1ZXN0RXh0ZW50aW9ucy5jcw==) | | |
| [...DiagnosticListener/AspNetCoreDiagnosticListener.cs](https://codecov.io/gh/elastic/apm-agent-dotnet/pull/731/diff?src=pr&el=tree#diff-c3JjL0VsYXN0aWMuQXBtLkFzcE5ldENvcmUvRGlhZ25vc3RpY0xpc3RlbmVyL0FzcE5ldENvcmVEaWFnbm9zdGljTGlzdGVuZXIuY3M=) | | |
| ... and [1 more](https://codecov.io/gh/elastic/apm-agent-dotnet/pull/731/diff?src=pr&el=tree-more) | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/elastic/apm-agent-dotnet/pull/731?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/elastic/apm-agent-dotnet/pull/731?src=pr&el=footer). Last update [460b007...b35bd4d](https://codecov.io/gh/elastic/apm-agent-dotnet/pull/731?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by gregkalapos** [comment]
> @gregkalapos. I messed up on the initial PR. EOL should include minors as well. That makes the date timeline much more realistic:
> [options="header"]
> |====
> |Agent version |EOL Date |Maintained until
> |1.0.x |2021-01-31 |1.1
> |1.1.x |2021-04-01 |1.2
> |1.2.x |2021-05-22 |1.3
> |1.3.x |2021-08-12 |1.4
> |====

Great! Yes, with that [my comment](https://github.com/elastic/apm-agent-dotnet/pull/731#pullrequestreview-360639747) is basically a non-issue. 👍

**Pull request merged**
