### PR TITLE
#2305 Remove polyfill packages

### PR DESCRIPTION
**Pull request by thompson-tomo**
The polyfil packages listed below will only be included in frameworks less than net 6 to reduce dependency graph

- System.Diagnostics.DiagnosticSource
- System.Reflection.Metadata
- System.Threading.Tasks.Dataflow
- System.Threading.Tasks.Extensions

Closes: #2305

### CODE REVIEW

**Comment by thompson-tomo** [comment]
@v1v is this something you could review?

**Comment by thompson-tomo** [comment]
Thanks @v1v

**Comment by Mpdreamz** [comment]
Hey @thompson-tomo we will get to this PR as soon as our current priorities allow!

The PR is much appreciated (like the others on our other repositories). 

The build of this repos is a bit more complicated so we have to carve out a little more time to review this then we did on the other PR's. 

I'm off on PTO now so can't dive in yet :)

**Comment by thompson-tomo** [comment]
Ok thanks for the update @Mpdreamz e joy the time off.

**Review by Mpdreamz — APPROVED** [review]
This LGTM!

Would love to clean this up a tad since we built this in a few different ways now. 

A regular nuget build which results in no dependencies (as verified on https://nuget.info/).

And a self contained build for the startup hooks zip files which will still include the dependency which I think is fine for now. 

Many thanks for taking this on @thompson-tomo ❤️

**Comment by thompson-tomo** [comment]
No problem at all @Mpdreamz glad I could help. 🙂

**Comment by Mpdreamz** [comment]
run docs-build

**Pull request merged**
