### PR TITLE
Grant read/execute to SQLite.Interop.dlls to IIS_USRS group

### PR DESCRIPTION
**Pull request by russcam**
This commit adds access to read/execute to the `IIS_USRS` group, which created ApplicationPoolIdentity accounts belong to.

When AspNetFullFramework.Tests are run with an application pool configured to use an ApplicationPoolIdentity, the pool may have insufficient access to execute the native SQLite.Interop.dlls used in database tests running with SQLite. ApplicationPoolIdentity accounts will not have access if the repository is cloned to and the application run under IIS from a privileged location, such as `%USERPROFILE%`.

This commit fixes this issue by configuring read and execute rights for the `IIS_USRS` group on the SQLite.Interop.dll files when configuring the ApplicationPool and using ApplicationPoolIdentity identity type.

### CODE REVIEW

**Review by gregkalapos — APPROVED** [review]
Thanks! 👍

**Comment by gregkalapos** [comment]
I also quickly looked at the failing windows test.... it should not be related. So I'd just merge this - maybe retrigger it once before the merge and see if it's green 😕

**Comment by russcam** [comment]
jenkins run the tests please

**Comment by russcam** [comment]
All checks have passed, merging this in.

**Pull request merged**
