### PR TITLE
Update configuration.asciidoc to include ElasticApm:SecretToken in AspNet Full example

### PR DESCRIPTION
**Pull request by rangler2**
Took me a while to figure out needed to add ElasticApm:SecretToken for AspNetFullFramework app to work, I propose it should be directly in the example config.

### CODE REVIEW

**Comment by rangler2** [comment]
Hi @gregkalapos 

Thanks, yes I agree. I've added the same to the .NET Core example now.

It was only because the onboarding within APM itself for .NET has an .NET Core example that includes the secret that I figured out it was missing. That is, because it has no .NET Framework example I had to find it from the docs.

image

In actual fact the onboarding suggests not only setting SecretToken and ServerUrls but also ServiceName, if it is best practice to always set this then maybe this should be in the example also?

Thanks,
Andy

**Comment by gregkalapos** [comment]
> Hi @gregkalapos
> 
> Thanks, yes I agree. I've added the same to the .NET Core example now.
> 
> It was only because the onboarding within APM itself for .NET has an .NET Core example that includes the secret that I figured out it was missing. That is, because it has no .NET Framework example I had to find it from the docs.
> 
> image
> 
> In actual fact the onboarding suggests not only setting SecretToken and ServerUrls but also ServiceName, if it is best practice to always set this then maybe this should be in the example also?
> 
> Thanks,
> Andy

Thanks Andy! 

Oh, that's a good point. Things from "Setup instruction" live in the Kibana repo. 
Now that you bring this up - actually ASP.NET Classic is not covered there, so we could extend that part. I opened https://github.com/elastic/apm-agent-dotnet/issues/719#issue-561761691 for that.

> In actual fact the onboarding suggests not only setting SecretToken and ServerUrls but also ServiceName, if it is best practice to always set this then maybe this should be in the example also?

Setting the `ServiceName` isn't really a best practice - we have an automatic service name detection mechanism in the agent, which has a couple of fallbacks, and worst case your service will be called "unknown" - that's the point when you should manually set it. But for the onboarding I'd say it's fine to rely on the auto detection, people should not be bothered by that.

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by bmorelli25** [comment]
Thanks @rangler2! Can you please sign the [Elastic contributor agreement](https://www.elastic.co/contributor-agreement) with your GitHub email address?

**Comment by bmorelli25** [comment]
@gregkalapos Is there an issue for .NET Agent <--> APM Server API keys? We'll probably want to update this documentation to `apikey` in the future.

**Comment by robgil** [comment]
# [Codecov](https://codecov.io/gh/elastic/apm-agent-dotnet/pull/714?src=pr&el=h1) Report
> Merging [#714](https://codecov.io/gh/elastic/apm-agent-dotnet/pull/714?src=pr&el=desc) into [1.x](https://codecov.io/gh/elastic/apm-agent-dotnet/commit/9714aa536f6aeb2521ed9986dea1eee8aecc5843&el=desc) will **not change** coverage by `%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/elastic/apm-agent-dotnet/pull/714?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##              1.x     #714   +/-   ##
=======================================
  Coverage   83.09%   83.09%           
=======================================
  Files         105      105           
  Lines        4401     4401           
=======================================
  Hits         3657     3657           
  Misses        744      744           
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/elastic/apm-agent-dotnet/pull/714?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/elastic/apm-agent-dotnet/pull/714?src=pr&el=footer). Last update [d3a6e2e...3d7758a](https://codecov.io/gh/elastic/apm-agent-dotnet/pull/714?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by gregkalapos** [comment]
> @gregkalapos Is there an issue for .NET Agent <--> APM Server API keys? We'll probably want to update this documentation to `apikey` in the future.

I just opened https://github.com/elastic/apm-agent-dotnet/issues/720.

**Comment by rangler2** [comment]
Sorry for holding this up, I have signed the CLA now. Thanks.

**Comment by gregkalapos** [comment]
> Sorry for holding this up, I have signed the CLA now. Thanks.

No worries; thanks for the PR! 

Merging now 🚀  🚀

**Pull request merged**
