### PR TITLE
Prepare Release 1.4.0

### PR DESCRIPTION
**Pull request by gregkalapos**
Preparing the new release - `1.4.0`.

### CODE REVIEW

**Comment by gregkalapos** [comment]
Ahh... Integration test fails, because the package version is already increased, so the integration test want to fetch that from nuget.org, but we have not yet pushed the new version, so it's not there. This is a 🐔 🥚  problem. 

```

[2020-03-19T13:01:11.326Z] error: Unable to find package Elastic.Apm.NetCoreAll with version (>= 1.4.0)
[2020-03-19T13:01:11.326Z] error:   - Found 8 version(s) in nuget.org [ Nearest version: 1.3.1 ]
[2020-03-19T13:01:11.326Z] error:   - Found 0 version(s) in local
```

**Comment by kuisathaverat** [comment]
chicken egg problem 😄 I think does not have a good solution 1.4.0 release doesn't exist at this point

**Comment by kuisathaverat** [comment]
ops!! moving the stage could make the trick

**Comment by gregkalapos** [comment]
The integration test issue is fixed in https://github.com/elastic/apm-integration-testing/pull/793. 

Once that's merged I'll re-trigger this.

**Comment by v1v** [comment]
Ready to be released now :)

**Pull request merged**
