### PR TITLE
Add runtime metrics - GC

### PR DESCRIPTION
**Pull request by gregkalapos**
Addressing https://github.com/elastic/apm-agent-dotnet/issues/321. 

In this round, I add GC metrics. 

Currently planned:

- `clr.gc.count`
- `clr.gc.gen0size`
- `clr.gc.gen1size`
- `clr.gc.gen2size`
- `clr.gc.gen3size`

The agent collects these metrics through EventSource on .NET Core and through Microsoft.Diagnostics.Tracing.TraceEvent (ETW) on Full Framework.

Changes in tests: We had lots of test that instantiated an `AgentComponents` and that started collecting all metrics and subscribed to `EventSource`. The tests run in parallel, so we had multiple `AgentComponents` subscribing and unsubscribing to `EventSource`, which does not seem to work. To avoid this (which does not happen in prod, so no reason to test for it at the moment) I adapted all tests to either use `TestAgentComponents` which does not collect metrics, or skip metrics collection in case a real `AgentComponents` is needed.

Some Lens visualization:

Heap sizes:

image

image

GC count over time:

image

### CODE REVIEW

**Comment by vhatsura** [comment]
@gregkalapos, as I understand, such metrics are accessible only for .Net Core 2.2 and higher. So, it would be nice to have a mechanism, which allows enabling specific metrics to provide by framework condition.

**Comment by gregkalapos** [comment]
> @gregkalapos, as I understand, such metrics are accessible only for .Net Core 2.2 and higher. So, it would be nice to have a mechanism, which allows enabling specific metrics to provide by framework condition.

That's a good point, but new PRs solved these: For Full Framework I added `Microsoft.Diagnostics.Tracing.TraceEvent` and we simply collect these through ETW - at least that's my current plan.

**Comment by gregkalapos** [comment]
@bmorelli25 jfyi there are some new doc lines here in `docs/metrics.asciidoc `.

**Comment by gregkalapos** [comment]
Failing test due to `The remote name could not be resolved: 'httpstat.us'`

 🤷‍♂ 😭 😢

**Comment by WillGunn** [comment]
I'm in the middle of running down a memory leak issue, and I believe its related to this change.

It looks like ETW tracing in full .net framework never releases the GCPerHeapHistory objects for the lifetime of the Trace, causing memory to grow everytime a GC ends.
image


As APM uses ETW tracing for garbage collection metrics, and keeps an ETW Tracing session active for the lifetime of the process, this causes the memory usage of the process using APM to keep growing.

**Pull request merged**
