### PR TITLE
Add Full Framework Web.config support to configure Elastic variables

### PR DESCRIPTION
**Pull request by NeoXtreem**
Addresses issue #275.

### CODE REVIEW

**Comment by lafriks** [comment]
Any chance on this getting in before stable release? Without this it is quite hard to integrate old-style asp.net websites on IIS with APM currently

**Comment by SergeyKleyman** [comment]
It's very unlikely since as you can see at
https://github.com/elastic/apm-agent-dotnet/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0
1.0 release is about to happen really really soon.

OTOH this issue is one of the top candidates for 1.1 so we will start working in near future.

**Comment by lafriks** [comment]
Is there anything I can help with this PR? I'm very interested in this to see it merged to have this in 1.1 version

**Comment by SergeyKleyman** [comment]
@lafriks If you would like to expedite this feature I would recommend
1. Strictly limiting changes to the feature (Web.config support for configuration). For example renaming `FullFrameworkConfigReader` and `MicrosoftExtensionsConfig` to `ApplicationConfigurationReader` as done in this PR doesn't seem to be relevant.
2. Adding tests
   - For example as as part of [`Elastic.Apm.AspNetFullFramework.Tests`](https://github.com/elastic/apm-agent-dotnet/tree/master/test/Elastic.Apm.AspNetFullFramework.Tests). At the moment there are tests that [set environment variables for IIS app pool](https://github.com/elastic/apm-agent-dotnet/blob/master/test/Elastic.Apm.AspNetFullFramework.Tests/IisAdministration.cs#L373) to test that reading configuration from environment variables works correctly - test infrastructure can be extended to write to `web.config`. But if you have alternative way to automate testing of this feature you suggestions are welcome.

**Comment by lafriks** [comment]
@SergeyKleyman I have created new PR #503 with tests also added

**Comment by SergeyKleyman** [comment]
@NeoXtreem This feature is implemented in #503. Would you mind if we close this PR?

**Comment by SergeyKleyman** [comment]
@NeoXtreem I'm closing this PR since this feature is implemented in #503. If there are some aspects of the feature not addressed in #503 please let us know by opening a new issue.

**Comment by NeoXtreem** [comment]
> @SergeyKleyman I have created new PR #503 with tests also added

@lafriks Thanks for implementing this change in another PR, but it would've been better to just become a collaborator on my fork and make your amendments (e.g., add tests) as required, as my changes included some changes (mostly cleanup, cosmetic and conforming to conventions) that I've now put in another PR (#587).

**Pull request closed without merging**
