### PR TITLE
ci(jenkins): support DinD

### PR DESCRIPTION
**Pull request by v1v**
Potentially to support https://github.com/jpetazzo/dind

## Tasks
- [x] Exposing the host docker socket inside the container.
- [x] Run DinD only if running in the CI  

## Tests
- Test execution 

image

image

## How to test this

```
docker build --tag sdk-linux-docker .ci/docker/sdk-linux 

docker run --rm -ti -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/app -w /app/test/Elastic.Apm.SqlClient.Tests -e BUILD_ID=1 sdk-linux-docker dotnet test
```

### CODE REVIEW

**Comment by v1v** [comment]
jenkins run the tests please

**Comment by cachedout** [comment]
I assume this has been discussed previously but just because I am curious, what is the reason for wanting DinD versus just exposing the host docker socket inside the container and letting the container start sibling containers? If there is an issue that describes this in more detail I would like to read it to learn more. Thanks!

**Comment by v1v** [comment]
@cachedout , likely I used the wrong term with DinD, I actually configured the main container with  the bind mount option, as you well described, see:
- https://github.com/elastic/apm-agent-dotnet/pull/678/commits/5eedc8291d38195f8b0d36e3e66704c7fb4b2270

This particular PR includes the above commit and https://github.com/elastic/apm-agent-dotnet/pull/678/commits/9defa954a72d28ae5b5d192d0e3b77504e158c6a in addition to  https://github.com/elastic/apm-agent-dotnet/pull/592

As soon as it works in our CI I'll close this PR and cherry-pick the changes. The intention of this PR was to work independently of the current upstream.

Thanks for asking :)

**Comment by cachedout** [comment]
Ahhh, OK. I understand now. Thanks for the clarification!

**Pull request closed without merging**
