### PR TITLE
Get the inner exception when capturing HttpUnhandledException

### LINKED ISSUE #941: Agent should use inner exception of HttpUnhandledException
In .NET Framework ASP.NET Web Forms an exception that escaped from the request handler is wrapped by the framework into `System.Web.HttpUnhandledException` and the original exception is stored as the inner exception of `System.Web.HttpUnhandledException`. The agent uses only `System.Web.HttpUnhandledException` for error event but instead it should the inner exception since this is what the application is actually thrown.

### PR DESCRIPTION
**Pull request by russcam**
This commit captures the inner exception
when an exception is a HttpUnhandledException.

Tidy up naming.

Closes #941

### CODE REVIEW

**Review by gregkalapos — COMMENTED** [review]
The code to capture the inner exception and the changes look good to me 👍 

If I see it correctly, there is no test covering this, right? It'd be nice to have a test case when `if (exception is HttpUnhandledException unhandledException)` is triggered and we assert on the captured error.

**Comment by russcam** [comment]
> If I see it correctly, there is no test covering this, right? It'd be nice to have a test case when if (exception is HttpUnhandledException unhandledException) is triggered and we assert on the captured error.

There's no test for this, adding one now. An interesting consequence of capturing the inner exception is that we lose the stacktrace, which is on the `HttpUnhandledException`. We _could_ 

1. Capture it with `CaptureError` and provide the `HttpUnhandledException` stacktrace, but it seems messy to construct the components to do this
2. Check for `System.Web.HttpUnhandledException` type in `ExecutionSegmentCommon.CaptureException(...)`, and if it has an inner exception, use the inner exception for the `CapturedException` with the stacktrace of `HttpUnhandledException` 
3. Allow an empty stacktrace in the ASP.NET FF testing framework (the test fails because an assertion is made that stack frames is not empty).

Thoughts?

Would it be useful to capture the base exception ([`exception.GetBaseException()`](https://docs.microsoft.com/en-us/dotnet/api/system.exception.getbaseexception?view=net-5.0)) in separate error fields in future?

**Comment by gregkalapos** [comment]
> > If I see it correctly, there is no test covering this, right? It'd be nice to have a test case when if (exception is HttpUnhandledException unhandledException) is triggered and we assert on the captured error.
> 
> There's no test for this, adding one now. An interesting consequence of capturing the inner exception is that we lose the stacktrace, which is on the `HttpUnhandledException`. We _could_
> 
> 1. Capture it with `CaptureError` and provide the `HttpUnhandledException` stacktrace, but it seems messy to construct the components to do this
> 2. Check for `System.Web.HttpUnhandledException` type in `ExecutionSegmentCommon.CaptureException(...)`, and if it has an inner exception, use the inner exception for the `CapturedException` with the stacktrace of `HttpUnhandledException`
> 3. Allow an empty stacktrace in the ASP.NET FF testing framework (the test fails because an assertion is made that stack frames is not empty).
> 
> Thoughts?
> 
> Would it be useful to capture the base exception ([`exception.GetBaseException()`](https://docs.microsoft.com/en-us/dotnet/api/system.exception.getbaseexception?view=net-5.0)) in separate error fields in future?

Oh, I see. Interesting.

I think option 2 won't work, because `HttpUnhandledException` lives in `System.Web.dll`, and `ExecutionSegmentCommon.CaptureException` is in `Elastic.Apm`, which does not reference `System.Web.dll` and it shouldn't do so, otherwise it'd pull in that dll in every environment.

Is the stacktrace on `HttpUnhandledException` the real stack trace from when the original exception is thrown? So does it contain the frame of the user code if an exception is thrown there? If so, I think option 1 isn't that bad, I'd just go with that. But if that's not a real stacktrace, then I think we should not bother to capture it, and option 3 is fine.

Btw - I blame `System.Web.dll` here. Why isn't the stacktrace on the inner exception? - not very logical  🤷 Anyways, that part we won't be able to change.

**Comment by russcam** [comment]
> I think option 2 won't work, because HttpUnhandledException lives in System.Web.dll, and ExecutionSegmentCommon.CaptureException is in Elastic.Apm, which does not reference System.Web.dll and it shouldn't do so, otherwise it'd pull in that dll in every environment.

We would just need to check the full type name of the exception, no reference needed. I'm not keen on this, as this logic really belongs only where `System.Web.HttpUnhandledException` can be thrown. Thought I'd put it forward for discussion nonetheless.

> Is the stacktrace on HttpUnhandledException the real stack trace from when the original exception is thrown? So does it contain the frame of the user code if an exception is thrown there? If so, I think option 1 isn't that bad, I'd just go with that. But if that's not a real stacktrace, then I think we should not bother to capture it, and option 3 is fine.

I'll see if I can come up with a test where the framework wraps in `HttpUnhandledException` rather than throwing this directly, to see. If there's no stacktrace for the inner exception, or the stacktrace of  `HttpUnhandledException` isn't that useful, I'd also lean towards option 3.

**Comment by russcam** [comment]
Have added a test where the framework wraps an exception in `HttpUnhandledException`. The inner exception has the stacktrace of where the error occurred, so this is good.

In a previous test, I was throwing a `HttpUnhandledException` directly inside a controller action, but this isn't a good representation of how the framework throws `HttpUnhandledException` from inside `System.Web.UI.Page.HandlerError(Exception)`.

**Review by gregkalapos — APPROVED** [review]
> The inner exception has the stacktrace of where the error occurred, so this is good.

🎉 great. 

PR looks good to me.

**Comment by russcam** [comment]
jenkins run the tests

**Comment by russcam** [comment]
failed tests are not related to this change. Merging in

**Pull request merged**
