### PR TITLE
Capture body feature

### LINKED ISSUE #435: When the request body is added for .net core?
Do you any plans to add the request body to the .net core configuration?

### PR DESCRIPTION
**Pull request by brezaie**
The CaptureBody feature is added to log the request and response bodies. This feature is boolean, either set to True or False.

Fixed #435

### CODE REVIEW

**Comment by gregkalapos** [comment]
Hi @brezaie,

This feature is already implemented in #402. Have you looked at that PR? We already had multiple iterations on it and it's basically just waiting for a last review. Is there anything not covered there? 

Given that we already spent a considerable time on #402 I'd keep that.

**Comment by brezaie** [comment]
Dear @gregkalapos,
Thanks for your comment. I was wondered if adding the feature takes too long. Thus, I decided to add it sooner to deploy it on our project.

**Comment by gregkalapos** [comment]
The review process is the same for every PR, so #402 is definitely closer to being merged.

**Comment by gregkalapos** [comment]
Hey @brezaie,

#402 got just merged. Would it be ok for you to close this one, since the functionality from this PR is already included on `master`?

**Comment by brezaie** [comment]
Thanks. Yes, I will close it.

**Pull request closed without merging**
