### PR TITLE
[APM-CI] msbuild testing

### PR DESCRIPTION
**Pull request by Conky5**
Testing of the msbuild stage with adjusted paths.

### CODE REVIEW

**Comment by gregkalapos** [comment]
Currently fails due to missing `netstandard` ref. Neither [this](https://github.com/dotnet/standard/issues/542#issuecomment-339328208) nor [this](https://github.com/dotnet/standard/issues/542#issuecomment-465375220) fixed it. Trying to come up with another fix...

**Comment by gregkalapos** [comment]
We still have the `dotnet sln remove sample/AspNetFullFrameworkSampleApp/AspNetFullFrameworkSampleApp.csproj` lines in the [`jenkinsfile`](https://github.com/elastic/apm-agent-dotnet/blob/5e75db5738e0fa97f4e336f824d1a4f88f3a10e9/Jenkinsfile#L76). I think all of those should be removed. I wonder why we even try to build that project...

**Comment by gregkalapos** [comment]
Update: by installing the whole "ASP.NET and web development" workload we made it green. 🎉

**Comment by Conky5** [comment]
@gregkalapos this works on the normal worker now, I'll leave this PR to be merged in by you or someone else on the team 😄.

**Pull request merged**
