### PR TITLE
add reference to Microsoft.NETFramework.ReferenceAssemblies

### LINKED ISSUE #470: Use Microsoft.NETFramework.ReferenceAssemblies
Followup from #444

Currently in case we build the solution on a non-Windows OS we don't generate `net461` targets.

The `Microsoft.NETFramework.ReferenceAssemblies` would solve this: https://github.com/dotnet/designs/pull/33#issuecomment-489264196

### PR DESCRIPTION
**Pull request by vhatsura**
for Elastic.Apm project

closes #470

### CODE REVIEW

**Comment by vhatsura** [comment]
@gregkalapos, good question. I'm using it for 3 months now (in my daily work and some OSS projects) and didn't have any issues with it. However, the final decision is up to you guys.

**Comment by gregkalapos** [comment]
We discusses this and we are not very confident with the preview package. We wait a little bit and see it it GAs in the near future. I'll leave this PR open and revisit. If `Microsoft.NETFramework.ReferenceAssemblies` remains preview too long we may come up with another approach. For now let's wait.

**Comment by Mpdreamz** [comment]
I'd love for this to be reconsidered, we've been using it on `elastic/elasticsearch-net` and others for a long time without issue.

**Comment by gregkalapos** [comment]
> I'd love for this to be reconsidered, we've been using it on `elastic/elasticsearch-net` and others for a long time without issue.

I'd also like to have this in. We had a long discussion with @SergeyKleyman in https://github.com/elastic/apm-agent-dotnet/issues/470 and then via zoom. @SergeyKleyman does not seem to be convinced and has concerns. 

I'd give my +1 to merge this. My main argument: we did not really do anything (or, well we did, we opened this, but it gets push back) to make sure https://github.com/elastic/apm-agent-dotnet/issues/444 never happens again - that issue can happen any time still. Merging this would make sure that never happens again, or worst case (assuming the new package does not work - which does not seem to be the case as stated above) we still have the same problem (which is building on non-Windows creates packages that don't work on `net461`).

**Comment by gregkalapos** [comment]
Done in https://github.com/elastic/apm-agent-dotnet/pull/426 - closing this now.

**Pull request closed without merging**
